### ISSUE TITLE
RuntimeWarning: coroutine 'GraphQLExtensionStack._handle_did_start.<locals>.end' was never awaited

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#251] opened 2021-09-19 03:29 UTC
**Describe the bug**

Testing https://github.com/cylc/cylc-flow/pull/4409 when I got this traceback in the logs. No idea what caused it, tried to reproduce it again (i.e. re-do the last commands I had done) with no luck.

Logging the issue in case anybody else sees it too. Searched and couldn't find this same error in the previous issues.

**Release version(s) and/or repository branch(es) affected?**

`master` on UIS, but Flow is on the linked PR branch.

**Steps to reproduce the bug**

I had stopped a workflow via GraphiQL, but the command failed due to an invalid enum value.

**Expected behavior**

Either no error or an error for the enum value I passed.

**Screenshots**

**Additional context**

```bash
[I 2021-09-19 15:25:28.445 CylcHubApp log:189] 101 GET /user/kinow/cylc/subscriptions (kinow@::1) 1.07ms
[I 2021-09-19 15:25:31.019 CylcHubApp log:189] 200 POST /user/kinow/cylc/graphql (kinow@::1) 1277.42ms
[I 2021-09-19 15:25:31.376 CylcHubApp log:189] 200 POST /user/kinow/cylc/graphql (kinow@::1) 2723.74ms
[W 2021-09-19 15:25:44.421 CylcHubApp log:189] 400 POST /user/kinow/cylc/graphql (kinow@::1) 1.29ms
/home/kinow/Development/python/workspace/cylc-uiserver/venv/lib/python3.8/site-packages/graphene_tornado/tornado_graphql_handler.py:268: RuntimeWarning: coroutine 'GraphQLExtensionStack._handle_did_start.<locals>.end' was never awaited
  validation_ended(validation_errors)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[W 2021-09-19 15:25:55.430 CylcHubApp log:189] 400 POST /user/kinow/cylc/graphql (kinow@::1) 5.90ms
[W 2021-09-19 15:26:02.594 CylcHubApp log:189] 400 POST /user/kinow/cylc/graphql (kinow@::1) 2.06ms
```

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by oliver-sanders** [comment] 2022-05-19 12:39
I think this may have been an issue with the `StopMode` enum which was misconfigured causing internal errors, fixed by https://github.com/cylc/cylc-flow/pull/4409.

I've not seen this in the wild and can't reproduce, stopping via GraphiQL works fine with the default or when manually specifying the stop mode e.g:

```graphql
mutation {
  stop(workflows: ["one"], mode: Now){ 
    result
  }
}
```
```json
{
  "data": {
    "stop": {
      "result": [
        {
          "id": "~/one",
          "response": [
            true,
            "Command queued"
          ]
        }
      ]
    }
  }
}
```

So closing this as fixed by https://github.com/cylc/cylc-flow/pull/4409 unless we are able to reproduce later.

**Closed by oliver-sanders** 2022-05-19 12:39 UTC
Labels: bug
