### ISSUE TITLE
Running workflow reported as paused

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-uiserver#220] opened 2021-05-19 03:17 UTC
**Describe the bug**

From Element, room web GUI

I spent some time this afternoon trying to reproduce https://github.com/cylc/cylc-ui/issues/668. I never got the JSON error. But I found a strange scenario.

1. Start everything and open a tab with the UI
2. Stop Hub (five is still running; five is part of my everything 🤣)
3. Start the Hub
4. Open another tab with the UI

Now if you pause/play the workflow from the two tabs (both should be showing the UI as online), the old tab will show nothing, or will show stale data. And it will try to pause when the workflow is playing, or vice verse. Which is a bug in the UI I think.

But... my other tab was always working... except this one time, which is still running as I type this.

- The UI is building normally
- `five` is happily running, spawning new tasks/cyclepoints (logs showing lines like `2021-05-19T14:58:43+12:00 INFO - (foo.20131012T1200+1200) spawned foo.20131013T0000+1200 flow(w) `)
- I opened the UI in **another new tab**
- It's showing like this:
- 
![image](https://user-images.githubusercontent.com/304786/118751474-77986700-b8b5-11eb-85d5-f2e0fc94895f.png)

For this tab, the `five` workflow is paused. If I click on the "Play" button, nothing changes in the UI. And in the workflow logs I get: `2021-05-19T15:00:26+12:00 WARNING - Cannot resume - workflow is not paused `

Fine, let me check with GraphiQL:

![image](https://user-images.githubusercontent.com/304786/118751429-664f5a80-b8b5-11eb-817e-8f3ea3b5490e.png)

But `five` **is running**:

![image](https://user-images.githubusercontent.com/304786/118751441-69e2e180-b8b5-11eb-8fd1-3fbfe55dbb56.png)

**Release version(s) and/or repository branch(es) affected?**

`master`

**Steps to reproduce the bug**

Above

**Expected behavior**

The UI shows the same state as in the UIS, which also reflects the state in the Workflow program.

**Screenshots**

Above

**Additional context**

**Pull requests welcome!**
This is an Open Source project - please consider contributing a bug fix
yourself (please read `CONTRIBUTING.md` before starting any work though).

**Comment by kinow** [comment] 2021-05-19 03:19
Note that GraphiQL does not share state with the rest of the UI application. That is useful to confirm whether a bug is happening in our code of the UI, or in the backend. In this case, since GraphiQL returns a message showing that the workflow is paused, while it's running, the problem is most likely not in the UI, but elsewhere (cannot tell whether UIS or Flow, sorry).

**Comment by kinow** [comment] 2021-05-19 03:45
Created a script in `/temp/test.sh` with code provided by @dwsutherland (thanks! :pray: ).

```bash
#!/bin/bash

# wsgraphql <workflow_name> <request_args_name>

read -r -d '' simple <<_args_
{
  "request_string": "
query {
  workflows{
    id
    name
    status
  }
}",
"variables": null
}
_args_

# Invoke command with given request
echo "${!2}"
time cylc client $1 graphql < <(echo ${!2})
```

Running it I got:

```bash
(venv) kinow@ranma:/tmp$ bash test.sh five simple
{
  "request_string": "
query {
  workflows{
    id
    name
    status
  }
}",
"variables": null
}
{
    "workflows": [
        {
            "id": "kinow|five",
            "name": "five",
            "status": "running"
        }
    ]
}

real	0m0.552s
user	0m0.491s
sys	0m0.059s
```

GraphiQL still shows it as `paused`.

![image](https://user-images.githubusercontent.com/304786/118753466-2f7b4380-b8b9-11eb-86a4-6f52b61894af.png)

**Comment by MetRonnie** [comment] 2021-10-07 16:26
Here is my attempt to reproduce this
1. >Start everything and open a tab with the UI

1. >Stop Hub (five is still running; five is part of my everything 🤣)

    I get the red "offline" pop-up as expected.

1. >Start the Hub

1. >Open another tab with the UI

    New tab: shows online dashboard. Original tab: still shows as offline. 

1. Open `five` (or `temp4` in my case - `temp` is love, `temp` is life) from the GScan sidebar

    New tab: shows `temp4` running correctly. Original tab: also starts showing `temp4` running correctly.

Tested in Firefox.

N.B. That was using `cylc hub`. Using `cylc gui`, the original tab almost immediately starts showing `temp4` running correctly after running `cylc gui` the second time.

**Comment by oliver-sanders** [comment] 2021-11-09 14:03
Can't reproduce. I think this has now been resolved by other changes.

Note a recent PR which fixed an issue where Scheduler attributes (e.g. workflow status) were not being updated in the data store correctly:

https://github.com/cylc/cylc-flow/pull/4464

Closing.

**Closed by oliver-sanders** 2021-11-09 14:03 UTC
Labels: bug, help wanted
