### ISSUE TITLE
Ping broken on the gui

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-uiserver#242] opened 2021-09-02 11:46 UTC
This appears with master `cylc-uiserver`, `cylc-ui` and `cylc-flow` installed.
Steps to reproduce: 

- Start either `cylc gui`, `jupyter-cylc` or `cylc hub` - issue is present with all three.
- Play a workflow, useful to run it in `--no-detach` mode to see the error on screen. 
- From the gui `ping` the workflow (with the ping button on the menu or from GraphIQL:
```
mutation {
  ping (workflows: ["workflow_name"]) {
    result
  }
}
``` 

You get a traceback error of....

```
Traceback (most recent call last):
  File "~/miniconda3/envs/cylc-8/lib/python3.7/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File "~/cylc-flow/cylc/flowwork/graphql.py", line 426, in async_resolve
    return await next_(root, info, **args)
  File "~/cylc-uiserver/cylc/uiserver/authorise.py", line 416, in async_resolve
    return await next_(root, info, **args)
  File "~/miniconda3/envs/cylc-8/lib/python3.7/site-packages/promise/iterate_promise.py", line 10, in iterate_promise
    yield from promise.future  # type: ignore
  File "~/miniconda3/envs/cylc-8/lib/python3.7/site-packages/promise/promise.py", line 844, in handle_future_result
    resolve(future.result())
  File " ~/cylc-flow/cylc/flowwork/schema.py", line 1277, in mutator
    res = await resolvers.mutator(info, command, w_args, args)
  File " ~/cylc-uiserver/cylc/uiserver/resolvers.py", line 201, in mutator
    'graphql', w_ids, graphql_args
  File " ~/cylc-uiserver/cylc/uiserver/workflows_mgr.py", line 305, in multi_request
    for msg_core in list(val.values())[0].get('result')
graphql.error.located_error.GraphQLLocatedError: 'list' object has no attribute 'values'
```

**Comment by kinow** [comment] 2021-09-14 03:06
@datamel I just tried calling it from GraphiQL and didn't get any error?

```graphql
mutation {
  ping (workflows: ["workflow_name"]) {
    result
  }
}
```

Are you able to confirm the issue is still occurring, please? 

Thanks!

**Comment by kinow** [comment] 2021-09-14 03:34
Oh, broken indeed. Just needed to run that against a running workflow :man_facepalming: 

![image](https://user-images.githubusercontent.com/304786/133190856-a895073f-ed4d-4f11-9d01-8676a1fc6d83.png)

**Comment by datamel** [comment] 2021-09-14 10:07
> Oh, broken indeed. Just needed to run that against a running workflow 🤦‍♂️
Woops, sorry, I should have made that clearer!

**Comment by MetRonnie** [comment] 2021-11-02 20:39
Closed by https://github.com/cylc/cylc-flow/pull/4481, leaving the traceback issue open here: https://github.com/cylc/cylc-uiserver/issues/271

**Closed by MetRonnie** 2021-11-02 20:39 UTC
Labels: bug, small
