### ISSUE TITLE
`cylc gui` should use the hub (if available)

### ISSUE THREAD

**Issue by datamel** [cylc/cylc-uiserver#382] opened 2022-08-23 14:11 UTC
In https://github.com/cylc/cylc-uiserver/pull/370, functionality was added so a uiserver launched by cylc gui would be reused by default on subsequent `cylc gui` commands.

`cylc hub` also launches a uiserver when the user visits the stated url. It would be ideal if cylc gui could detect (and open with) an already launched uiserver from the cylc hub command. 

In order for implementation, we will need to add functionality for the site to configure the hub url.  `cylc gui` logic will need updating to redirect to this hub if it is running. Authentication in this case will need consideration.

**Comment by datamel** [comment] 2022-08-23 15:20
Note for implementation:

In `hubapp.py` we will need to set (and unset)the `JUPYTER_RUNTIME_DIR` variable. This will ensure the jp-server pid file gets saved in the correct folder so it can be discovered by `cylc gui` logic.

The pid file (if selected) will need its url adapting as the currently created file will direct to a 404.

**Comment by datamel** [comment] 2022-08-24 11:04
Update: the site needs to configure the url. `cylc gui` should redirect to the hub if it is running. Implementation should bypass the pid file.

**Comment by oliver-sanders** [comment] 2023-07-17 16:18
Duplicate of #238

**Closed by oliver-sanders** 2023-07-17 16:18 UTC
